name: Build and Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code từ repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Đăng nhập Docker Hub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}  # Docker Hub username
        password: ${{secrets.DOCKER_PASSWORD}}  # Docker Hub token

    # Build và push Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/200lab-final-project:latest
        
  deploy:
    runs-on: ubuntu-latest
    needs: build # Chỉ chạy khi job build thành công
    
    steps:
    # SSH vào EC2 và deploy
    - name: Deploy on EC2
      env:
        KEY: ${{secrets.EC2_SSH_KEY}}    # Private key SSH của EC2
        HOST: ${{secrets.EC2_HOST}}      # IP hoặc hostname của EC2
        USER: ${{secrets.EC2_USER}}      # Username SSH
      run: |
        echo "$KEY" > key.pem
        chmod 400 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST << 'EOF'
        
        # Dừng container cũ nếu đang chạy
        docker stop 200lab-final-project || true
        docker rm 200lab-final-project || true
        docker rmi 200lab-final-project:latest || true

        # Pull image từ Docker Hub
        docker pull ${{secrets.DOCKER_USERNAME}}/200lab-final-project:latest

        # Chạy container mới
        docker run -d -p 80:8080 --name 200lab-final-project ${{secrets.DOCKER_USERNAME }}/200lab-final-project:latest
        EOF

